development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cspm_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://:your_password@localhost:6379/1
  channel_prefix: cspm_production
